config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'static/index'
  root 'static#index'
  get 'dashboard' => 'dashboard#index'
  resources :projects
  resources :time_estimates
  resources :time_entries
  resources :companies do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :company
  has_many :time_estimates
  has_many :time_entries
  has_and_belongs_to_many :tasks
  has_many :projects, -> { distinct }, through: :tasks


  def full_name
    first_name + " " + last_name
  end

  def billed_hours
    hours = 0
    billed_hours = time_entries.where('start_time <= ?', Time.now.beginning_of_day)
    billed_hours.each do |billed|
      hours += billed.hours
    end
    hours
  end

  def future_hours
    hours = 0
    estimates = time_estimates.where('start_time >= ?', Time.now.beginning_of_day)
    estimates.each do |estimate|
      hours += estimate.hours
    end
    hours
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    company = Company.create(name: params[:user][:company])
    super do
      resource.admin = true
      resource.company_id = company.id
      resource.permissions = [{"team"=>"0", "projects"=>"0", "dashboard"=>"0", "forecasting"=>"0"}]
      resource.save
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'dashboard'
  load_and_authorize_resource

  def index
    @users = User.accessible_by(current_ability)
  end

  def show
  end

  def new
    @dashboard_permission = nil
    @forecasting_permission = nil
    @projects_permission = nil
    @team_permission = nil
  end

  def create
    @user = User.new(resource_params)
    @user.company_id = current_user.company_id
    if @user.invite!(current_user)
      redirect_to company_users_path
    else
      render new_company_user_path
    end
  end

  def edit
    @dashboard_permission = @user['permissions'][0]['dashboard']
    @forecasting_permission =  @user['permissions'][0]['forecasting']
    @projects_permission =  @user['permissions'][0]['projects']
    @team_permission =  @user['permissions'][0]['team']
  end

  def update
    if @user.update(resource_params)
      redirect_to company_users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy

    redirect_to company_users_path
  end

  private
    def resource_params
      params.require(:user).permit(:first_name, :last_name, :email, :admin, permissions: [:dashboard, :forecasting, :projects, :team])
    end
end

app/views/users/_dropdown.html.erb
<div>
  <div x-data="{ open: false }" @keydown.escape="open = false" @click.away="open = false" class="relative inline-block text-left">
    <div>
      <span class="rounded-md shadow-sm">
        <button @click="open = !open" type="button" class="inline-flex justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition ease-in-out duration-150">
          Actions
          <svg class="-mr-1 ml-2 h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"/>
          </svg>
        </button>
      </span>
    </div>
    <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-right absolute right-0 mt-2 rounded-md shadow-lg z-10">
      <div class="rounded-md bg-white shadow-xs">
        <div class="py-1">
          <%= link_to(edit_company_user_path(current_user.company, user), class: 'group flex items-center px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900') do %>
            <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-500 group-focus:text-gray-500" viewBox="0 0 20 20" fill="currentColor">
              <path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"/>
              <path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"/>
            </svg>
            Edit
          <% end %>
          <%= link_to(company_user_path(current_user.company, user), method: :delete, data: { confirm: "Are you sure you want to delete #{user.full_name}?" }, class: 'group flex items-center px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900') do %>
            <svg class="mr-3 h-5 w-5 text-gray-400 group-hover:text-gray-500 group-focus:text-gray-500" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"/>
            </svg>
            Delete
          <% end %>
        </div>
      </div>
    </div>
  </div>
  </div>

app/views/users/_form.html.erb
<div class="mt-6">
  <div class="md:grid md:grid-cols-3 md:gap-6">
    <div class="mt-5 md:mt-0 md:col-span-3">
      <form action="#" method="POST">
        <div class="shadow sm:rounded-md sm:overflow-hidden">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-3 gap-6">
              <div class="col-span-1 sm:col-span-1">
                <label for="username" class="block text-sm font-medium leading-5 text-gray-700">
                  First Name
                </label>
                <div class="mt-1 flex rounded-md shadow-sm">
                  <%= form.text_field :first_name, autofocus: true, class: "form-input rounded-md flex-1 block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5"  %>
                </div>
              </div>
              <div class="col-span-1 sm:col-span-1">
                <label for="username" class="block text-sm font-medium leading-5 text-gray-700">
                  Last Name
                </label>
                <div class="mt-1 flex rounded-md shadow-sm">
                  <%= form.text_field :last_name, autofocus: true, class: "form-input rounded-md flex-1 block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5"  %>
                </div>
              </div>
            </div>

            <div class="grid grid-cols-3 gap-6 mt-4">
              <div class="col-span-1 sm:col-span-1">
                <label for="username" class="block text-sm font-medium leading-5 text-gray-700">
                  Email Address
                </label>
                <div class="mt-1 flex rounded-md shadow-sm">
                  <%= form.text_field :email, autofocus: true, class: "form-input rounded-md flex-1 block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5"  %>
                </div>
              </div>
            </div>

            <div class="grid grid-cols-6 gap-6 mt-4">
              <div class="col-span-1 sm:col-span-1">
                <label for="username" class="block text-sm font-medium leading-5 text-gray-700">
                  Admin?
                </label>
                <div class="mt-1 flex rounded-md shadow-sm">
                  <%= select(:user, :admin, [['No', false], ['Yes', true]], { selected: @user.admin }, { class: 'block form-select w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5' }) %>
                </div>
              </div>
            </div>

            <div>
              <label for="username" class="mt-4 block text-sm font-medium leading-5 text-gray-700 mb-4">
                Permissions
              </label>
              <div class="grid grid-cols-8 gap-6 mt-1 bg-gray-50">
                <div class="p-4 col-span-2 sm:col-span-2">
                  <div>
                    <label class="block text-sm font-medium leading-5 text-gray-700 ">Dashboard</label>
                    <div class="mt-1 flex rounded-md shadow-sm">
                      <%= form.select 'permissions[][dashboard]', [['Cannot View', '0'], ['Can View', '1']], { selected: @dashboard_permission }, { class: 'block form-select w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5'} %>
                    </div>
                  </div>
                </div>
                <div class="p-4 col-span-2 sm:col-span-2">
                  <div>
                    <label class="block text-sm font-medium leading-5 text-gray-700 ">Forecasting</label>
                    <div class="mt-1 flex rounded-md shadow-sm">
                      <%= form.select 'permissions[][forecasting]', [['View/Edit Themselves', 0], ['View Others', 1], ['View/Edit Others', 2]], { selected: @forecasting_permission }, { class: 'block form-select w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5' } %>
                    </div>
                  </div>
                </div>
                <div class="p-4 col-span-2 sm:col-span-2">
                  <div>
                    <label class="block text-sm font-medium leading-5 text-gray-700 ">Projects</label>
                    <div class="mt-1 flex rounded-md shadow-sm">
                      <%= form.select 'permissions[][projects]', [['Cannot View', 0], ['Can View', 1], ['Can Edit', 2]], { selected: @projects_permission }, { class: 'block form-select w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5' } %>
                    </div>
                  </div>
                </div>
                <div class="p-4 col-span-2 sm:col-span-2">
                  <div>
                    <label class="block text-sm font-medium leading-5 text-gray-700 ">Team Members</label>
                    <div class="mt-1 flex rounded-md shadow-sm">
                      <%= form.select 'permissions[][team]', [['Cannot View', 0], ['Can View', 1], ['Can Edit', 2]], { selected: @team_permission }, { class: 'block form-select w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5' } %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="px-4 py-3 bg-gray-50 text-left sm:px-6">
            <span class="inline-flex rounded-md shadow-sm">
              <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition duration-150 ease-in-out">
                <%= button_text %>
              </button>
            </span>
            <span class="inline-flex rounded-md shadow-sm">
              <%= link_to "Cancel", company_users_path, class: 'inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-gray-600 bg-white hover:text-gray-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition duration-150 ease-in-out ml-3' %>
            </span>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="md:flex md:items-center md:justify-between">
  <div class="flex-1 min-w-0">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
      Edit User
    </h2>
  </div>
</div>
<%= form_with(scope: :user, url: company_user_path, local: true, method: 'put') do |form| %>
  <%= render 'form', form: form, button_text: 'Save' %>
<% end %>

app/views/users/index.html.erb
<div class="md:flex md:items-center md:justify-between">
  <div class="flex-1 min-w-0">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
      Users
    </h2>
  </div>
  <% if can? :create, User %>
    <div class="mt-4 flex md:mt-0 md:ml-4">
      <span class="inline-flex rounded-md shadow-sm">
        <%= link_to fa_icon("plus", text: "New User"), new_company_user_path(current_user.company), class: 'inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition ease-in-out duration-150', type: 'button' %>
      </span>
    </div>
  <% end %>
</div>

<div class="mt-4">
  <div class="flex flex-col">
    <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
      <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
        <table class="min-w-full">
          <thead>
            <tr>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Email
              </th>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Completed Hours
              </th>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Estimated Future Hours
              </th>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              </th>
            </tr>
          </thead>
          <tbody class="bg-white">
            <% if @users.empty? %>
              <tr>
                <td class="p-10 text-center text-gray-500 text-sm" colspan="5">No team members yet. Let's add some now!</td>
              </tr>
            <% end %>
            <% @users.each do |user| %>
              <tr>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                  <div class="flex items-center">
                    <div class="ml-4">
                      <% if can? :update, User %>
                        <%= link_to user.full_name, edit_company_user_path(current_user.company, user), class: 'text-sm leading-5 font-medium text-gray-900' %>
                      <% else %>
                        <%= user.full_name %>
                      <% end %>
                    </div>
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                  <div class="text-sm leading-5 text-gray-500"><%= user.email %></div>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                  <%= user.billed_hours %>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
                  <%= user.future_hours %>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
                  <%= render partial: 'dropdown', locals: { user: user } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="md:flex md:items-center md:justify-between">
  <div class="flex-1 min-w-0">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
      Create User
    </h2>
  </div>
</div>
<%= form_with(scope: :user, url: company_users_path(current_user.company), local: true) do |form| %>
  <%= render 'form', form: form, button_text: 'Create' %>
<% end %>