config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'static/index'
  root 'static#index'
  get 'dashboard' => 'dashboard#index'
  resources :projects
  resources :time_estimates
  resources :time_entries
  resources :companies do
    resources :users
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :company
  has_many :time_entries
  has_many :tasks
  has_many :users, -> { distinct }, through: :tasks
  has_many :time_estimates, -> { distinct }, through: :tasks
  has_many :time_entries, -> { distinct }, through: :tasks
  enum billing_type: [:fixed, :time_and_materials]
  accepts_nested_attributes_for :tasks,
    allow_destroy: true,
    :reject_if => proc { |att| att[:title].blank? }
  default_scope { order(title: :asc) }

  def billed_hours
    hours = 0
    billed_hours = time_entries.where('start_time <= ?', Time.now.beginning_of_day)
    billed_hours.each do |billed|
      hours += billed.hours
    end
    hours
  end

  def future_hours
    hours = 0
    estimates = time_estimates.where('start_time >= ?', Time.now.beginning_of_day)
    estimates.each do |estimate|
      hours += estimate.hours
    end
    hours
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  load_and_authorize_resource

  def index
    @projects = Project.accessible_by(current_ability)
  end

  def show
  end

  def new
    @project.tasks.build
  end

  def create
    @project = Project.new(project_params)
    @project.company_id = current_user.company_id
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def edit
    @project.tasks.build
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy

    redirect_to projects_path
  end

  private
    def project_params
      params.require(:project).permit(:title, :description, :billing_type, :hours_budget, tasks_attributes: [:id, :title, :billable, user_ids: []])
    end
end

app/views/projects/_form.html.erb
<%= form_with model: @project, local: true do |form| %>
  <div class="mt-6">
    <div class="md:grid md:grid-cols-3 md:gap-6">
      <div class="mt-5 md:mt-0 md:col-span-3">
        <form action="#" method="POST">
          <div class="shadow sm:rounded-md sm:overflow-hidden">
            <div class="px-4 py-5 bg-white sm:p-6">
              <div class="grid grid-cols-3 gap-6">
                <div class="col-span-3 sm:col-span-2">
                  <label for="username" class="block text-sm font-medium leading-5 text-gray-700">
                    Name
                  </label>
                  <div class="mt-1 flex rounded-md shadow-sm">
                    <%= form.text_field :title, autofocus: true, class: "form-input rounded-md flex-1 block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", placeholder: "Enter Project Name"  %>
                  </div>
                </div>
              </div>

              <div class="mt-6 p-4 bg-gray-50">
                <label class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
                  Hour Tracking Categories
                </label>
                <%= form.fields_for :tasks do |task| %>
                  <div class="grid grid-cols-6 gap-4 mt-4 hour-field-group">
                    <div class="col-span-1">
                      <label class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
                        Billable?
                      </label>
                      <%= task.select :billable, [['Billable', true], ['Non-Billable', false]], {}, { class: 'block form-select w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5' } %>
                    </div>
                    <div class="col-span-2">
                      <label class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
                        Name
                      </label>
                      <%= task.text_field :title, autofocus: true, class: "form-input rounded-md flex-1 block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", placeholder: "Enter Project Name"  %>
                    </div>
                    <div class="sm:col-span-3">
                      <label class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
                        Users
                      </label>
                      <div class="mt-1 sm:mt-0">
                        <div class="rounded-md shadow-sm">
                          <%= task.collection_select(:user_ids, current_user.company.users, :id, :full_name, {prompt: false}, {multiple: true, class: 'chosen chosen-select block form-select w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5', id: 'project_user_ids', data: {placeholder: 'Select User(s)'}}) %>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>

              <div class="mt-2">
                <label class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
                  Billing Type
                </label>
                <div class="mt-1 sm:mt-0 sm:col-span-2">
                  <div class="max-w-xs rounded-md shadow-sm">
                    <%= form.select :billing_type, [['Fixed Price', 'fixed'], ['Time & Materials', 'time_and_materials']], { selected: @projects_permission }, { class: 'block form-select w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5' } %>
                  </div>
                </div>
              </div>

              <div class="mt-6">
                <label class="block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2">
                  Budget (Hours)
                </label>
                <div class="mt-1 sm:mt-0 sm:col-span-2">
                  <div class="max-w-xs rounded-md shadow-sm">
                    <%= form.number_field :hours_budget, autofocus: true, class: "form-input rounded-md flex-1 block w-full rounded-none rounded-r-md transition duration-150 ease-in-out sm:text-sm sm:leading-5", placeholder: "Enter Budgeted Hours"  %>
                  </div>
                </div>
              </div>

              <div class="mt-6">
                <label for="about" class="block text-sm leading-5 font-medium text-gray-700">
                  Description
                </label>
                <div class="rounded-md shadow-sm">
                  <%= form.text_area :description, class: "form-textarea mt-1 block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5", placeholder: "Write a brief description of what the project entails."  %>
                </div>
              </div>
            </div>
            <div class="px-4 py-3 bg-gray-50 text-left sm:px-6">
              <span class="inline-flex rounded-md shadow-sm">
                <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition duration-150 ease-in-out">
                  <%= button_text %>
                </button>
              </span>
              <span class="inline-flex rounded-md shadow-sm">
                <%= link_to "Cancel", projects_url, class: 'inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-gray-600 bg-white hover:text-gray-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition duration-150 ease-in-out ml-3' %>
              </span>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div>
  <div class="md:flex md:items-center md:justify-between">
    <div class="flex-1 min-w-0">
      <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
        Edit Project
      </h2>
    </div>
  </div>
</div>

<%= render 'form', button_text: 'Update Project'  %>

app/views/projects/index.html.erb
<div class="md:flex md:items-center md:justify-between">
  <div class="flex-1 min-w-0">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
      Projects
    </h2>
  </div>
  <% if can? :update, Project %>
    <div class="mt-4 flex md:mt-0 md:ml-4">
      <span class="inline-flex rounded-md shadow-sm">
        <%= link_to fa_icon("plus", text: "New Project"), new_project_path, class: 'inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition ease-in-out duration-150', type: 'button' %>
      </span>
    </div>
  <% end %>
</div>

<div class="mt-4">
  <div class="flex flex-col">
    <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
      <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
        <table class="min-w-full">
          <thead>
            <tr>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Description
              </th>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Completed Hours
              </th>
              <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                Estimated Future Hours
              </th>
            </tr>
          </thead>
          <tbody class="bg-white">
            <% if @projects.empty? %>
              <tr>
                <td class="p-10 text-center text-gray-500 text-sm" colspan="5">No projects created yet. Create project for you employees to start tracking time against.</td>
              </tr>
            <% end %>
            <% @projects.each do |project| %>
              <tr>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                  <div class="flex items-center">
                    <div class="ml-4">
                      <%= link_to project.title, project_path(project), class: 'text-sm leading-5 font-medium text-gray-900' %>
                    </div>
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                  <div class="text-sm leading-5 text-gray-500"><%= project.description %></div>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200">
                  <%= project.billed_hours %>
                </td>
                <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-500">
                  <%= project.future_hours %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="md:flex md:items-center md:justify-between">
  <div class="flex-1 min-w-0">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
      Create A Project
    </h2>
  </div>
</div>

<%= render 'form', button_text: 'Create Project'  %>

app/views/projects/show.html.erb
<div>
  <div class="bg-white shadow overflow-hidden  sm:rounded-lg">
    <div class="bg-white px-4 py-5 border-b border-gray-200 sm:px-6">
      <div class="-ml-4 -mt-2 flex items-center justify-between flex-wrap sm:flex-no-wrap">
        <div class="ml-4 mt-2">
          <h3 class="text-lg leading-6 font-medium text-gray-900">
            <%= @project.title %>
          </h3>
        </div>
        <% if can? :update, Project %>
          <div class="ml-4 mt-2 flex-shrink-0">
            <%= link_to 'Delete Project', project_path(@project), method: :delete, data: { confirm: "Are you sure you want to delete #{@project.title}?" } %>
            <span class="inline-flex rounded-md shadow-sm">
              <%= link_to 'Edit Project', edit_project_path(@project), class: 'relative inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700' %>
            </span>
          </div>
        <% end %>
      </div>
    </div>
    <div class="px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 col-gap-4 row-gap-8 sm:grid-cols-2">
        <div class="sm:col-span-1">
          <dt class="text-sm leading-5 font-medium text-gray-500">
            Assigned Users
          </dt>
          <dd class="mt-1 text-sm leading-5 text-gray-900">
            <%= @project.users.map(&:full_name).join(', ') %>
          </dd>
        </div>
        <div class="sm:col-span-2">
          <dt class="text-sm leading-5 font-medium text-gray-500">
            Project Description
          </dt>
          <dd class="mt-1 text-sm leading-5 text-gray-900">
            <%= @project.description %>
          </dd>
        </div>
        <div class="sm:col-span-2">
          <dt class="text-sm leading-5 font-medium text-gray-500">
            Progress
          </dt>
          <dd class="mt-4 text-sm leading-5 text-gray-900 rounded-md border border-gray-100 h-64 flex items-center justify-center">
            Project Related Graphs and Charts Here
          </dd>
        </div>
      </dl>
    </div>
  </div>
</div>